/*
 * This file is generated by jOOQ.
*/
package com.jooq.demo.domain.tables.records;


import com.jooq.demo.domain.tables.RoleResource;

import javax.annotation.Generated;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleResourceRecord extends UpdatableRecordImpl<RoleResourceRecord> implements Record5<Integer, Integer, Integer, DateTime, DateTime> {

    private static final long serialVersionUID = 1751315826;

    /**
     * Setter for <code>test.role_resource.id</code>.
     */
    public RoleResourceRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>test.role_resource.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.role_resource.role_id</code>.
     */
    public RoleResourceRecord setRoleId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>test.role_resource.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>test.role_resource.resource_id</code>.
     */
    public RoleResourceRecord setResourceId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>test.role_resource.resource_id</code>.
     */
    public Integer getResourceId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>test.role_resource.create_time</code>.
     */
    public RoleResourceRecord setCreateTime(DateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>test.role_resource.create_time</code>.
     */
    public DateTime getCreateTime() {
        return (DateTime) get(3);
    }

    /**
     * Setter for <code>test.role_resource.update_time</code>.
     */
    public RoleResourceRecord setUpdateTime(DateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>test.role_resource.update_time</code>.
     */
    public DateTime getUpdateTime() {
        return (DateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, DateTime, DateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, DateTime, DateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RoleResource.ROLE_RESOURCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RoleResource.ROLE_RESOURCE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RoleResource.ROLE_RESOURCE.RESOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<DateTime> field4() {
        return RoleResource.ROLE_RESOURCE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<DateTime> field5() {
        return RoleResource.ROLE_RESOURCE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getResourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DateTime value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DateTime value5() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleResourceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleResourceRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleResourceRecord value3(Integer value) {
        setResourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleResourceRecord value4(DateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleResourceRecord value5(DateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleResourceRecord values(Integer value1, Integer value2, Integer value3, DateTime value4, DateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleResourceRecord
     */
    public RoleResourceRecord() {
        super(RoleResource.ROLE_RESOURCE);
    }

    /**
     * Create a detached, initialised RoleResourceRecord
     */
    public RoleResourceRecord(Integer id, Integer roleId, Integer resourceId, DateTime createTime, DateTime updateTime) {
        super(RoleResource.ROLE_RESOURCE);

        set(0, id);
        set(1, roleId);
        set(2, resourceId);
        set(3, createTime);
        set(4, updateTime);
    }
}
