/*
 * This file is generated by jOOQ.
*/
package com.jooq.demo.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.joda.time.DateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Admin implements Serializable {

    private static final long serialVersionUID = 181154078;

    private Integer  id;
    private String   username;
    private String   password;
    private String   nickName;
    private String   address;
    private Integer  isDel;
    private DateTime createdTime;
    private DateTime updatedTime;

    public Admin() {}

    public Admin(Admin value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.nickName = value.nickName;
        this.address = value.address;
        this.isDel = value.isDel;
        this.createdTime = value.createdTime;
        this.updatedTime = value.updatedTime;
    }

    public Admin(
        Integer  id,
        String   username,
        String   password,
        String   nickName,
        String   address,
        Integer  isDel,
        DateTime createdTime,
        DateTime updatedTime
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.nickName = nickName;
        this.address = address;
        this.isDel = isDel;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
    }

    public Integer getId() {
        return this.id;
    }

    public Admin setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getUsername() {
        return this.username;
    }

    public Admin setUsername(String username) {
        this.username = username;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public Admin setPassword(String password) {
        this.password = password;
        return this;
    }

    public String getNickName() {
        return this.nickName;
    }

    public Admin setNickName(String nickName) {
        this.nickName = nickName;
        return this;
    }

    public String getAddress() {
        return this.address;
    }

    public Admin setAddress(String address) {
        this.address = address;
        return this;
    }

    public Integer getIsDel() {
        return this.isDel;
    }

    public Admin setIsDel(Integer isDel) {
        this.isDel = isDel;
        return this;
    }

    public DateTime getCreatedTime() {
        return this.createdTime;
    }

    public Admin setCreatedTime(DateTime createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    public DateTime getUpdatedTime() {
        return this.updatedTime;
    }

    public Admin setUpdatedTime(DateTime updatedTime) {
        this.updatedTime = updatedTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Admin (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(nickName);
        sb.append(", ").append(address);
        sb.append(", ").append(isDel);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updatedTime);

        sb.append(")");
        return sb.toString();
    }
}
