/*
 * This file is generated by jOOQ.
*/
package com.jooq.demo.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.joda.time.DateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Resource implements Serializable {

    private static final long serialVersionUID = 1821664653;

    private Integer  id;
    private Integer  parentId;
    private String   parentIds;
    private String   name;
    private String   url;
    private Integer  status;
    private DateTime createTime;
    private DateTime updateTime;
    private String   permission;

    public Resource() {}

    public Resource(Resource value) {
        this.id = value.id;
        this.parentId = value.parentId;
        this.parentIds = value.parentIds;
        this.name = value.name;
        this.url = value.url;
        this.status = value.status;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.permission = value.permission;
    }

    public Resource(
        Integer  id,
        Integer  parentId,
        String   parentIds,
        String   name,
        String   url,
        Integer  status,
        DateTime createTime,
        DateTime updateTime,
        String   permission
    ) {
        this.id = id;
        this.parentId = parentId;
        this.parentIds = parentIds;
        this.name = name;
        this.url = url;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.permission = permission;
    }

    public Integer getId() {
        return this.id;
    }

    public Resource setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getParentId() {
        return this.parentId;
    }

    public Resource setParentId(Integer parentId) {
        this.parentId = parentId;
        return this;
    }

    public String getParentIds() {
        return this.parentIds;
    }

    public Resource setParentIds(String parentIds) {
        this.parentIds = parentIds;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Resource setName(String name) {
        this.name = name;
        return this;
    }

    public String getUrl() {
        return this.url;
    }

    public Resource setUrl(String url) {
        this.url = url;
        return this;
    }

    public Integer getStatus() {
        return this.status;
    }

    public Resource setStatus(Integer status) {
        this.status = status;
        return this;
    }

    public DateTime getCreateTime() {
        return this.createTime;
    }

    public Resource setCreateTime(DateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    public DateTime getUpdateTime() {
        return this.updateTime;
    }

    public Resource setUpdateTime(DateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    public String getPermission() {
        return this.permission;
    }

    public Resource setPermission(String permission) {
        this.permission = permission;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Resource (");

        sb.append(id);
        sb.append(", ").append(parentId);
        sb.append(", ").append(parentIds);
        sb.append(", ").append(name);
        sb.append(", ").append(url);
        sb.append(", ").append(status);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(permission);

        sb.append(")");
        return sb.toString();
    }
}
