/*
 * This file is generated by jOOQ.
*/
package com.jooq.demo.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.joda.time.DateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

    private static final long serialVersionUID = 791859183;

    private Integer  id;
    private String   roleName;
    private Integer  isDel;
    private DateTime createTime;
    private DateTime updateTime;

    public Role() {}

    public Role(Role value) {
        this.id = value.id;
        this.roleName = value.roleName;
        this.isDel = value.isDel;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public Role(
        Integer  id,
        String   roleName,
        Integer  isDel,
        DateTime createTime,
        DateTime updateTime
    ) {
        this.id = id;
        this.roleName = roleName;
        this.isDel = isDel;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public Role setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public Role setRoleName(String roleName) {
        this.roleName = roleName;
        return this;
    }

    public Integer getIsDel() {
        return this.isDel;
    }

    public Role setIsDel(Integer isDel) {
        this.isDel = isDel;
        return this;
    }

    public DateTime getCreateTime() {
        return this.createTime;
    }

    public Role setCreateTime(DateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    public DateTime getUpdateTime() {
        return this.updateTime;
    }

    public Role setUpdateTime(DateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(roleName);
        sb.append(", ").append(isDel);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
