/**
 * This class is generated by jOOQ
 */
package com.jooq.demo.domain;


import com.jooq.demo.domain.tables.Admin;
import com.jooq.demo.domain.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table test.admin
	 */
	public static final Admin ADMIN = com.jooq.demo.domain.tables.Admin.ADMIN;

	/**
	 * The table test.user
	 */
	public static final User USER = com.jooq.demo.domain.tables.User.USER;
}
