/*
 * This file is generated by jOOQ.
*/
package com.jooq.demo.domain;


import com.jooq.demo.domain.tables.Admin;
import com.jooq.demo.domain.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.admin</code>.
     */
    public static final Admin ADMIN = com.jooq.demo.domain.tables.Admin.ADMIN;

    /**
     * The table <code>test.user</code>.
     */
    public static final User USER = com.jooq.demo.domain.tables.User.USER;
}
