DROP TABLE IF EXISTS role;

CREATE TABLE `role` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`role_name` VARCHAR(20) NOT NULL DEFAULT '',
`is_del` int(11) DEFAULT '0',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS user_role;

CREATE TABLE `user_role` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`role_id` int(11) NOT NULL ,
`user_id` int(11) NOT NULL ,
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`id`),
 FOREIGN KEY (user_id) REFERENCES user(id),
 FOREIGN KEY (role_id) REFERENCES role(id)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;