
CREATE TABLE IF NOT EXISTS `resource` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`parent_id` INT(11),
`parent_ids` VARCHAR(20),
`name` VARCHAR(20) NOT NULL DEFAULT '',
`url` VARCHAR(20) NOT NULL DEFAULT '',
`status` int(11) DEFAULT '0',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `role_resource` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`role_id` int(11) NOT NULL ,
`resource_id` int(11) NOT NULL ,
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`id`),
 FOREIGN KEY (resource_id) REFERENCES resource(id),
 FOREIGN KEY (role_id) REFERENCES role(id)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;